// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYUYoDiKsAic-PhiozflURImSiDXnG0g',
    appId: '1:598911837649:web:1be5870490127787b46cf0',
    messagingSenderId: '598911837649',
    projectId: 'phoneauth-ef0b3',
    authDomain: 'phoneauth-ef0b3.firebaseapp.com',
    storageBucket: 'phoneauth-ef0b3.appspot.com',
    measurementId: 'G-FKNH82YH6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBerKUbvqK-icjaryMDeisKaRHStxtrvrI',
    appId: '1:598911837649:android:1b3856ddcef84122b46cf0',
    messagingSenderId: '598911837649',
    projectId: 'phoneauth-ef0b3',
    storageBucket: 'phoneauth-ef0b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOPt5-x3IADMRpb9Ji2tMkhldZgmD2U4',
    appId: '1:598911837649:ios:d3b759bed9b4e812b46cf0',
    messagingSenderId: '598911837649',
    projectId: 'phoneauth-ef0b3',
    storageBucket: 'phoneauth-ef0b3.appspot.com',
    iosBundleId: 'com.example.phoneAuthAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOPt5-x3IADMRpb9Ji2tMkhldZgmD2U4',
    appId: '1:598911837649:ios:d3b759bed9b4e812b46cf0',
    messagingSenderId: '598911837649',
    projectId: 'phoneauth-ef0b3',
    storageBucket: 'phoneauth-ef0b3.appspot.com',
    iosBundleId: 'com.example.phoneAuthAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYUYoDiKsAic-PhiozflURImSiDXnG0g',
    appId: '1:598911837649:web:0d1d590f6fb575a2b46cf0',
    messagingSenderId: '598911837649',
    projectId: 'phoneauth-ef0b3',
    authDomain: 'phoneauth-ef0b3.firebaseapp.com',
    storageBucket: 'phoneauth-ef0b3.appspot.com',
    measurementId: 'G-KQN26C58XS',
  );
}